import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
  Link
} from "@react-pdf/renderer";

import fs from "fs";



const styles = StyleSheet.create({

  page: {

    padding:40,

    fontSize:12,

    fontFamily:"Helvetica"

  },


  logo:{

    width:120,

    marginBottom:25

  },


  title:{

    fontSize:22,

    marginBottom:10,

    fontWeight:"bold"

  },


  subtitle:{

    fontSize:13,

    marginBottom:20

  },


  box:{

    padding:15,

    backgroundColor:"#f3f4f6",

    marginVertical:15

  },


  label:{

    fontSize:12

  },


  bigNumber:{

    fontSize:24,

    marginVertical:8

  },


  heading:{

    fontSize:16,

    marginTop:20,

    marginBottom:10

  },


  item:{

    marginBottom:8

  },


  button:{

    marginTop:20,

    backgroundColor:"#111827",

    color:"#ffffff",

    padding:12,

    textAlign:"center"

  },


  footer:{

    marginTop:40,

    fontSize:10

  }


});

function getLogoBase64() {

  const logoPath =
    process.cwd() + "/public/logo.png";


  const logo = fs.readFileSync(logoPath);


  return `data:image/png;base64,${logo.toString("base64")}`;

}





export default function RevenueReportPDF({

 data

}:{

 data:any

}){


const logo = getLogoBase64();


return (

<Document>


<Page size="A4" style={styles.page}>


<Image

src={logo}

style={styles.logo}

/>


<Text style={styles.title}>

Missed-Call Revenue Recovery Report

</Text>



<Text style={styles.subtitle}>

Dental Practice Revenue Assessment

</Text>




<View style={styles.box}>


<Text style={styles.label}>

Estimated Monthly Revenue Opportunity

</Text>


<Text style={styles.bigNumber}>

${data.lost_revenue_monthly.toLocaleString()}

</Text>



<Text style={styles.label}>

Estimated Annual Revenue Opportunity

</Text>


<Text style={styles.bigNumber}>

${data.lost_revenue_yearly.toLocaleString()}

</Text>



</View>





<Text style={styles.heading}>

Where Revenue Is Being Lost

</Text>



<Text style={styles.item}>

✓ Missed patient enquiries are not converted

</Text>


<Text style={styles.item}>

✓ Calls outside working hours are lost

</Text>


<Text style={styles.item}>

✓ Slow follow-up reduces appointments

</Text>





<Text style={styles.heading}>

AI Receptionist Recovery Strategy

</Text>



<Text style={styles.item}>

✓ Answers missed calls instantly

</Text>


<Text style={styles.item}>

✓ Captures patient information

</Text>


<Text style={styles.item}>

✓ Helps convert enquiries into bookings

</Text>






<Link

src="https://calendly.com/cleavondigital/marketing-ai-growth-strategy-session"

style={styles.button}

>

Book AI Receptionist Strategy Call

</Link>






<Text style={styles.footer}>

Generated by Cleavon Digital

{"\n"}

AI Revenue Systems for Dental Practices

</Text>



</Page>


</Document>

);


}